package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetAllApplicationsParams creates a new GetAllApplicationsParams object
// with the default values initialized.
func NewGetAllApplicationsParams() GetAllApplicationsParams {
	var ()
	return GetAllApplicationsParams{}
}

// GetAllApplicationsParams contains all the bound params for the get all applications operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAllApplications
type GetAllApplicationsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The Docker repository name
	  Required: true
	  In: path
	*/
	Repository string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetAllApplicationsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rRepository, rhkRepository, _ := route.Params.GetOK("repository")
	if err := o.bindRepository(rRepository, rhkRepository, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAllApplicationsParams) bindRepository(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Repository = raw

	return nil
}
