package main

import (
	"os"
	"strconv"

	"github.com/30x/shipyard/pkg/server"
	// "github.com/30x/shipyard/pkg/shipyard"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	portString := os.Getenv("PORT")

	if portString == "" {
		shipyard.LogError.Fatal("You must specifiy the PORT environment variable")
	}

	port, err := strconv.Atoi(portString)

	if err != nil {
		shipyard.LogError.Fatal("You must specify a valid integer for the PORT value")
	}

	imageCreator, error = shipyard.NewImageCreatorFromEnv()

	//we should die here if we're unable to start
	if error != nil {
		shipyard.LogError.Fatalf("Unable to create image creator %s", error)
	}

	server := server.NewServer(imageCreator)

	if err := server.Start(port); err != nil {
		shipyard.LogError.Fatalln(err)
	}
}
