package main

import (
	"os"
	"strconv"

	"github.com/30x/shipyard/pkg/server"
	"github.com/30x/shipyard/pkg/shipyard"
)

// This file was generated by the swagger tool.
// Make sure not to overwrite this file after you generated it because all your edits would be lost!

func main() {

	server := server.NewServer()
	portString := os.Getenv("PORT")

	if portString == "" {
		shipyard.LogError.Fatal("You must specifiy the PORT environment variable")
	}

	port, err := strconv.Atoi(portString)

	if err != nil {
		shipyard.LogError.Fatal("You must specify a valid integer for the PORT value")
	}

	if err := server.Start(port); err != nil {
		shipyard.LogError.Fatalln(err)
	}
}
