swagger: '2.0'
info:
  version: 0.0.0
  title: APIs for building docker images.
basePath: /beeswax/images/api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  '/builds':
    post:
      description: Create an image of the specified revision
      operationId: createApplication
      consumes:
        - multipart/form-data
      produces:
        - text/plain encoding=utf-8
      responses:
        '201':
          description: The request was for a valid repo, application, and image.  The image was created
          schema:
            $ref: '#/definitions/Image'
        '409':
          description: Application and image already exists
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: The namespace and application does not exist
          schema:
            $ref: '#/definitions/Error'
      parameters:
        - name: application
          in: formData
          description: The Application name
          required: true
          type: string
        - name: revision
          in: formData
          description: The Revision of the image
          required: true
          type: string
        - name: file
          in: formData
          description: The file data as a multipart
          required: true
          type: file
        - name: publicPath
          in: formData
          description: The public path of the application in the format of [PORT]:[URL]. For example, 8080:/ or 9000:/foo/bar
          required: true
          type: string
        - name: envVar
          in: formData
          description: An optional array of environment variables for the image
          type: array
          items:
            type: string
  '/namespaces':
    get:
      description: Get all namespaces
      operationId: getAllNamespaces
      responses:
        '200':
          description: The request was for a namespaces
          schema:
            type: array
            items:
              $ref: '#/definitions/Namespace'
  '/namespaces/{namespace}/applications':
    get:
      description: Get all applications for this namespace
      operationId: getAllApplications
      responses:
        '200':
          description: The request was for a namespace and applications exist within that namespace
          schema:
            type: array
            items:
              $ref: '#/definitions/Application'
        '404':
          description: The request was for a namespace that does not exist
          schema:
            $ref: '#/definitions/Error'
      parameters:
        - $ref: '#/parameters/namespace'
  '/namespaces/{namespace}/apps/{application}/images':
    get:
      description: Get all built images for the application in the namespace
      operationId: getImageRevisions
      responses:
        '200':
          description: The request was for a valid namespace and application
          schema:
            type: array
            items:
              $ref: '#/definitions/Image'
        '404':
          description: The request was for a namespace or application that does not exist
          schema:
            $ref: '#/definitions/Error'
    parameters:
      - $ref: '#/parameters/namespace'
      - $ref: '#/parameters/application'
  '/namespaces/{namespace}/apps/{application}/images/{revision}':
    get:
      description: Get the image for the specfied revision of the application within the repo
      operationId: getImage
      responses:
        '200':
          description: The request was for a valid namespace and application and revision
          schema:
            $ref: '#/definitions/Image'
        '404':
          description: The request was for a namespace, application, or revision that does not exist
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: Delete the image for the specfied revision of the application within the repo
      operationId: deleteImage
      responses:
        '200':
          description: The request was for a valid namespace and application and revision
          schema:
            $ref: '#/definitions/Image'
        '404':
          description: The request was for a namespace, application, or revision that does not exist
          schema:
            $ref: '#/definitions/Error'
    parameters:
      - $ref: '#/parameters/namespace'
      - $ref: '#/parameters/application'
      - $ref: '#/parameters/revision'
definitions:
  Image:
    description: An image of an application and revision
    allOf:
      - $ref: '#/definitions/Links'
      - type: object
        properties:
          created:
            description: The timestamp the image was created
            type: string
            format: date-time
          size:
            description: 'The size of the image, in bytes'
            type: integer
          imageId:
            description: The docker image id SHA
            type: string
          logs:
            type: array
            items:
              type: string
            description: The logs from the build
        required:
          - created
          - size
          - imageId
          - logs
  Namespace:
    description: A namespace
    allOf:
      - $ref: '#/definitions/Links'
      - type: object
        properties:
          name:
            description: The name of the application
            type: string
        required:
          - name
  Application:
    description: An application
    allOf:
      - $ref: '#/definitions/Links'
      - type: object
        properties:
          name:
            description: The name of the application
            type: string
        required:
          - name
  Error:
    description: Object used for all API errors.
    type: object
    properties:
      message:
        type: string
      logs:
        type: array
        items:
          type: string
    required:
      - message
  Links:
    description: Object used to wrap resource links.
    type: object
    properties:
      _links:
        description: Container for any number of named resource links.
        type: object
        additionalProperties:
          description: A resource link.
          type: object
          properties:
            href:
              description: The link to the resource.
              format: uri
              type: string
          required:
            - href
    required:
      - _links
parameters:
  namespace:
    name: namespace
    in: path
    description: The Docker namespace name
    required: true
    type: string
  application:
    name: application
    in: path
    description: The Application name
    required: true
    type: string
  revision:
    name: revision
    in: path
    description: The revision of the application
    required: true
    type: string
tags:
  - name: deploy
    description: Deploy operation
