package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/middleware"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetImageRevisionsParams creates a new GetImageRevisionsParams object
// with the default values initialized.
func NewGetImageRevisionsParams() GetImageRevisionsParams {
	var ()
	return GetImageRevisionsParams{}
}

// GetImageRevisionsParams contains all the bound params for the get image revisions operation
// typically these are obtained from a http.Request
//
// swagger:parameters getImageRevisions
type GetImageRevisionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*The Application name
	  Required: true
	  In: path
	*/
	Application string
	/*The Docker repository name
	  Required: true
	  In: path
	*/
	Repository string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetImageRevisionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rApplication, rhkApplication, _ := route.Params.GetOK("application")
	if err := o.bindApplication(rApplication, rhkApplication, route.Formats); err != nil {
		res = append(res, err)
	}

	rRepository, rhkRepository, _ := route.Params.GetOK("repository")
	if err := o.bindRepository(rRepository, rhkRepository, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetImageRevisionsParams) bindApplication(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Application = raw

	return nil
}

func (o *GetImageRevisionsParams) bindRepository(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Repository = raw

	return nil
}
