package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetAllApplicationsParams creates a new GetAllApplicationsParams object
// with the default values initialized.
func NewGetAllApplicationsParams() *GetAllApplicationsParams {
	var ()
	return &GetAllApplicationsParams{}
}

/*GetAllApplicationsParams contains all the parameters to send to the API endpoint
for the get all applications operation typically these are written to a http.Request
*/
type GetAllApplicationsParams struct {

	/*Repository
	  The Docker repository name

	*/
	Repository string
}

// WithRepository adds the repository to the get all applications params
func (o *GetAllApplicationsParams) WithRepository(repository string) *GetAllApplicationsParams {
	o.Repository = repository
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllApplicationsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param repository
	if err := r.SetPathParam("repository", o.Repository); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
