package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	httptransport "github.com/go-swagger/go-swagger/httpkit/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/30x/shipyard/pkg/client/client/operations"
)

// Default apis for building docker images HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new apis for building docker images HTTP client.
func NewHTTPClient(formats strfmt.Registry) *ApisForBuildingDockerImages {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost", "/", []string{"http"})
	return New(transport, formats)
}

// New creates a new apis for building docker images client
func New(transport client.Transport, formats strfmt.Registry) *ApisForBuildingDockerImages {
	cli := new(ApisForBuildingDockerImages)
	cli.Transport = transport

	cli.Operations = operations.New(transport, formats)

	return cli
}

// ApisForBuildingDockerImages is a client for apis for building docker images
type ApisForBuildingDockerImages struct {
	Operations *operations.Client

	Transport client.Transport
}

// SetTransport changes the transport on the client and all its subresources
func (c *ApisForBuildingDockerImages) SetTransport(transport client.Transport) {
	c.Transport = transport

	c.Operations.SetTransport(transport)

}
