apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shipyard
  labels:
    name: shipyard
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: shipyard
        routable: "true"
      annotations:
        privateHosts: "shipyard.e2e.local"
        privatePaths: "5280:/beeswax/images"
        # Remove for deployment because we DO NOT want direct access to these services
        publicHosts: "ingress.e2e.local"
        publicPaths: "5280:/beeswax/images"
    spec:
      containers:
      - image: registry-1.docker.io/thirtyx/shipyard:0.0.2.build.8
        imagePullPolicy: Always
        name: shipyard
        ports:
        - containerPort: 5280
        env:
        - name: PORT
          value: "5280"
        - name: DOCKER_PROVIDER
          value: ecr
        - name: DOCKER_REGISTRY_URL
          valueFrom:
            secretKeyRef:
              name: docker-config
              key: host
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: POD_PROVIDER
          value: s3
        - name: S3_BUCKET
          value: e2e-podtemplatespec
        - name: S3_REGION
          value: us-west-2
        - name: ECR_REGION
          value: us-west-2
        - name: ECR_TIMEOUT
          value: "5"
        - name: SHUTDOWN_TIMEOUT
          value: "60"
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-access
              key: key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-access
              key: secret
        volumeMounts:
        - mountPath: /root/.docker
          name: clientconfig
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: dockersocket
          readOnly: false
      volumes:
      - name: clientconfig
        secret:
          secretName: docker-config
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
