apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kiln
  labels:
    name: kiln
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kiln
        routable: "true"
      annotations:
        publicHosts: "sso.k8s.local"
        publicPaths: "5280:/imagespaces"
        privateHosts: "sso.k8s.local"
        privatePaths: "5280:/imagespaces"
    spec:
      containers:
      - image: thirtyx/kiln:local
        imagePullPolicy: IfNotPresent
        name: kiln
        ports:
        - containerPort: 5280
        env:
        - name: PORT
          value: "5280"
        - name: DOCKER_PROVIDER
          value: docker
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: POD_PROVIDER
          value: local
        - name: SHUTDOWN_TIMEOUT
          value: "60"
        - name: AUTH_API_HOST
          value: api.e2e.apigee.net
        - name: NO_REAP
          value: "true"
        - name: LOCAL_REGISTRY_ONLY
          value: "true"
        - name: LOCAL_DIR
          value: /tmp/storagedir
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersocket
          readOnly: false

      volumes:
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock