apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shipyard
  labels:
    name: shipyard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: shipyard
        routable: "true"
      annotations:
        publicHosts: "test.k8s.local"
        publicPaths: "5280:/imagespaces"
        projectcalico.org/policy: "allow tcp from cidr 192.168.0.0/16; allow tcp from cidr 10.129.0.0/16"
    spec:
      containers:
      - image: localhost:5000/thirtyx/shipyard
        imagePullPolicy: Always
        name: shipyard
        ports:
        - containerPort: 5280
        env:
        - name: PORT
          value: "5280"
        - name: DOCKER_PROVIDER
          value: docker
        - name: DOCKER_REGISTRY_URL
          value: localhost:5000
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: POD_PROVIDER
          value: local
        - name: SHUTDOWN_TIMEOUT
          value: "60"
        - name: AUTH_API_HOST
          value: api.e2e.apigee.net
        - name: REAP_INTERVAL
          value: "60"
          # Leave images < 5 minutes old
        - name: REAP_MIN_AGE
          value: "300"
        - name: SELF_BASE_URL
          value: "http://localhost:5280"
        - name: LOCAL_DIR
          value: /tmp/storagedir
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersocket
          readOnly: false

      volumes:
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
