apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shipyard
  labels:
    name: shipyard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: shipyard
        microservice: "true"
      annotations:
        trafficHosts: "deploy.k8s.local"
        publicPaths: "5280:/beeswax/images"
    spec:
      containers:
      - image: thirtyx/shipyard:latest
        imagePullPolicy: Always
        name: shipyard
        ports:
        - containerPort: 5280
        env:
        - name: PORT
          value: "5280"
        - name: DOCKER_PROVIDER
          value: docker
        - name: DOCKER_REGISTRY_URL
          value: 172.17.4.99:5000
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        - name: POD_PROVIDER
          value: local
        - name: LOCAL_DIR
          value: /tmp/storagedir
        - name: SHUTDOWN_TIMEOUT
          value: "60"
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersocket
          readOnly: false
      volumes:
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
