apiVersion: v1
kind: ReplicationController
metadata:
  name: app1
  labels:
    app: app1
    version: '0.1'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app1
        version: '0.1'
    spec:
      containers:
      - name: app1
        image: ubuntu/xenial
        ports:
        - containerPort: 80
  selector:
    app: app1
    version: '0.1'
