apiVersion: v1
kind: ReplicationController
metadata:
  name: app2
  labels:
    app: app2
    version: '0.1'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app2
        version: '0.1'
    spec:
      containers:
      - name: app1
        image: tnine/app2
        ports:
        - containerPort: 80
  selector:
    app: app2
    version: '0.1'
