apiVersion: v1
kind: Service
metadata:
  name:  app2
  labels:
    app:  app2
    version: '0.1'
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: app2
    version: '0.1'
